### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by weppami** [Ybansan/crestapps-bootstrap4-templates#1]
Hi, CrestApp 2.3.2

Problem 1
    - Installation request for ybansan/crestapps-bootstrap4-templates 2.2.11 -> satisfiable by ybansan/crestapps-bootstrap4-templates[v2.2.11].
    - ybansan/crestapps-bootstrap4-templates v2.2.11 requires crestapps/laravel-code-generator ~2.2.11 -> satisfiable by crestapps/laravel-code-generator[v2.2.11, v2.2.12, v2.2.13, v2.2.14] but these conflict with your requirements or minimum-stability.

**Comment by Ybansan** [comment]
Hi, 
Which CrestApps/laravel-code-generator version do you use?

**Comment by weppami** [comment]
CrestApp 2.3.2

I had to install the template manually and it works, the only part that does not work is the validation, help-block and has-error are not supported anymore in bs4. I can send you my modified portion if you will

**Comment by Ybansan** [comment]
Yes, I will. But I don't have time immediately to integrate it. I'll do it later. Thank's

**Comment by Ybansan** [comment]
Hi pgferro. I have some free time now. I'll be pleased if you send me your modifications. Regards.

**Comment by weppami** [comment]
The javascript in app.blade :

 // Sets the validator defaults
                $.validator.setDefaults({
                errorElement: "div",
                highlight: function (element, errorClass, validClass) {
                    $(element).closest('.form-control').addClass('is-invalid');
                },
                unhighlight: function (element, errorClass, validClass) {
                    $(element).closest('.form-control').removeClass('is-invalid').addClass('is-valid');
                },
                errorPlacement: function (error, element) {
                    error.addClass('invalid-feedback');
                    if (element.parent('.input-group').length) {
                        error.insertAfter(element.parent());
                    } else if(element.prop('type') === 'checkbox' || element.prop('type') === 'radio') {
                        error.appendTo(element.closest(':not(input, label, .checkbox, .radio)').first());
                    } else {
                        error.insertAfter(element);
                    }
                }
            });

In form.blade, the portion containing the display error 

`{!! $errors->first('field_id', '<div class="">:message</p>') !!}`

Let me know if it works for you ..

Cheers

**Comment by Ybansan** [comment]
Hi pgferro. I updated te package with your proposal. I just changed:
`{!! $errors->first('field_id', '<div class="">:message</p>') !!}`
With
`{!! $errors->first('[% field_name %]', '<p class="form-text text-muted">:message</p>') !!}`
I also simplified the publication part of the package.
I did not had time to test all your code. I will do it soon in a new Laravel project.
Thank you for your help :-)

**Comment by Ybansan** [comment]
Pgferro proposal merged.
